[package]
name = "raynaldo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bevy_color = "0.15.4"
embree4-rs = { git = "https://github.com/ivsop/embree4-rs/", rev = "18c1084caac9de959e76280716ed1dd71e9824eb" }
embree4-sys = "0.0.12"
fastrand = "2.3.0"
glam = "0.30.0"
image = "0.25.5"
rand = "0.9.0"
rayon = "1.10.0"
